# Generated by Django 4.1.7 on 2023-06-15 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=300)),
                ('info', models.TextField()),
                ('img', models.ImageField(upload_to='img')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realty.category_realty')),
            ],
        ),
    ]
